// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwomajdxcbtbsmbaucro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3b21hamR4Y2J0YnNtYmF1Y3JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTIzNjQsImV4cCI6MjA3MjA2ODM2NH0.-KNdEw2KnsROoMNMkb11BSnOKT2EcxOXWk6-7NWVZZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});